name       : osmo
version    : 0.4.0
release    : 4
source     :
    - http://managedway.dl.sourceforge.net/project/osmo-pim/osmo-pim/osmo-0.4.0/osmo-0.4.0-1.tar.gz : fb454718e071c44bd360ce3e56cb29926cbf44a0d06ec738fa9b40fe3cbf8a33
license    : GPL-2.0
component  : office.notes
summary    : Osmo is a handy personal organizer, which includes calendar, tasks manager,
    address book and notes modules.
description: |
    Osmo is a handy personal organizer, which includes calendar, tasks manager, address book and notes modules.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(libarchive)
    - pkgconfig(libical)
    - pkgconfig(libnotify)
    - pkgconfig(pango)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
